### ISSUE TITLE
Fix error reporting

### ISSUE THREAD

**Issue by bjartek** [bjartek/overflow#149]
What transaction was run that had this error, give more context in error
```=== FAIL: .  (0.00s)
panic: execution error code 1: [Error Code: 1101] error caused by: 1 error occurred:
	* transaction preprocess failed: [Error Code: 1101] cadence runtime error: Execution failed:
error: cannot access `save`: function requires `Storage | SaveValue` authorization, but reference only has `BorrowValue` authorization
  --> 5cf669f700d87ba1fee74507384d4b573c60459ef33b9a593958f64f0b376431:18:12
   |
18 |             account.storage.save(<- Dandy.createEmptyCollection(), to: Dandy.CollectionStoragePath)
   |             ^^^^^^^^^^^^^^^^^^^^

error: cannot access `issue`: function requires `Capabilities | StorageCapabilities | IssueStorageCapabilityController` authorization, but reference only has `BorrowValue` authorization
  --> 5cf669f700d87ba1fee74507384d4b573c60459ef33b9a593958f64f0b376431:19:22
   |
19 |             let cap = account.capabilities.storage.issue<&Dandy.Collection>(Dandy.CollectionStoragePath)
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: cannot access `publish`: function requires `Capabilities | PublishCapability` authorization, but reference only has `BorrowValue` authorization
  --> 5cf669f700d87ba1fee74507384d4b573c60459ef33b9a593958f64f0b376431:20:12
   |
20 |             account.capabilities.publish(cap, at: Dandy.CollectionPublicPath)
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^




goroutine 1 [running]:
github.com/bjartek/overflow.OverflowInteractionBuilder.Send({{0x0, 0x0}, {0x1039004b3, 0x9}, 0x0, 0x140008cc000, {0x1039004b3, 0x9}, {0x0, 0x0}, ...})
	/Users/bjartek/go/pkg/mod/github.com/bjartek/overflow@v1.14.1-0.20231220114203-b4d28262f2dc/interaction_builder.go:571 +0xe1c
github.com/bjartek/overflow.(*OverflowState).Tx(0x140008cc000, {0x1039004b3?, 0xa?}, {0x14001306ae0?, 0x103ec4ee0?, 0xe2e5289a91e4a9a2?})
	/Users/bjartek/go/pkg/mod/github.com/bjartek/overflow@v1.14.1-0.20231220114203-b4d28262f2dc/state.go:585 +0x9c
github.com/findonflow/find.SetupFIND.(*OverflowState).TxFN.func2(...)
	/Users/bjartek/go/pkg/mod/github.com/bjartek/overflow@v1.14.1-0.20231220114203-b4d28262f2dc/state.go:570
github.com/findonflow/find.SetupFIND(0x140008cc000)
	/Users/bjartek/dev/find/setup_test.go:162 +0x1840
github.com/bjartek/overflow.SetupTest({0x140009c3e58, 0x2, 0x140009c3e68?}, 0x1041f3230)
	/Users/bjartek/go/pkg/mod/github.com/bjartek/overflow@v1.14.1-0.20231220114203-b4d28262f2dc/testing.go:65 +0xf8
github.com/findonflow/find.TestMain(0x1400008e688?)
	/Users/bjartek/dev/find/setup_test.go:19 +0x70
main.main()
	_testmain.go:123 +0x1ac
exit status 2
FAIL	github.com/findonflow/find	4.291s

DONE 0 tests, 1 failure in 6.388```

**Comment by bjartek** [comment]
i added the location of the filename in stable-cadence branch. Not sure if signer and/or arguments are needed here.
